version: '3.5'

services: 
   sql-server:
      container_name: secret_sql-server
      image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
      environment: 
         - PUID=1000
         - PGID=1000
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Anac0nda
      networks:
         - secret-net
      ports:
         - 1433:1433
     # volumes: 
        # - /var/opt/mssql:/home/martin/Docker/Appdata/ms-sql/
        # - ~/Docker/Appdata/secret/sql-server/:/var/opt/mssql #TODO: Fix this later
   api: 
      container_name: secret_api
      build:
         context: dotnetapi/
      networks: 
         - secret-net
      ports:
         - 8000:80

   proxy:
      container_name: secret_proxy
      build:
         context: proxymodule/
      networks: 
         - secret-net
      entrypoint: '/bin/sh -c "/root/.local/bin/mitmproxy -p8080 -s /home/mitmproxy/.mitmproxy/anatomy.py"'
      #entrypoint: 'proxymodule/./entrypoint.sh'
      ports: 
         - 8080:8080 
      stdin_open: true # docker run -i
      tty: true # docker run -t
      volumes: 
         - ~/Docker/Appdata/secret/proxymodule/:/home/mitmproxy/.mitmproxy

networks:
   secret-net:
      driver: bridge
