version: '3.5'

services: 
   # This container holds the database
   secret_mssql:
      container_name: secret_mssql
      image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
      environment: 
         - PUID=1000
         - PGID=1000
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Anac0nda
      networks:
         - secret_net
      ports:
         - 1433:1433
      volumes: 
         - ${docker_dir}/sql/:/var/opt/mssql
   
   # This container holds the api
   secret_user_api: 
      container_name: secret_user_api
      build:
         context: user_api/
      environment: 
         - PUID=1000
         - PGID=1000
      networks: 
         - secret_net
      ports:
         - 8000:80

   # This container holds mitm-proxy and our python script
   secret_mitm:
      container_name: secret_mitm
      build:
         context: mitm/
      environment: 
         - PUID=1000
         - PGID=1000
      networks: 
         - secret_net
      ports: 
         - 8080:8080 
      stdin_open: true # docker run -i
      tty: true # docker run -t
      volumes: 
         - ${docker_dir}/mitm/:/home/mitmproxy/.mitmproxy

# By creating a vlan for all of the microservices, we can reference each one by it's
# container name instead of IP address in all of our code
networks:
   secret_net:
      driver: bridge
